### Obtener todas las tareas
GET http://127.0.0.1:8000/api/tareas/?last_doc_id=ozRxq6Rrdu6CfJA1kldF
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjM3MzAwNzY5YTA3ZTA1MTE2ZjdlNTEzOGZhOTA5MzY4NWVlYmMyNDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZWNvLXRlY2gtOWRmZWEiLCJhdWQiOiJlY28tdGVjaC05ZGZlYSIsImF1dGhfdGltZSI6MTc3NDQxMjAzMywidXNlcl9pZCI6IlI2OTd4MW81VzVPRFpqcFlhbkJSYkFEektndTEiLCJzdWIiOiJSNjk3eDFvNVc1T0RaanBZYW5CUmJBRHpLZ3UxIiwiaWF0IjoxNzc0NDEyMDMzLCJleHAiOjE3NzQ0MTU2MzMsImVtYWlsIjoiamF2aWVyQGdtYWlsLmNvbSIsImVtYWxzX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqYXZpZXJAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.dAeCNVHhX5Ps3lBHjeblPX_cgZMugymOmZXt_JzEpOYQUoIjlrpnF5RYBmaIc-Dx0mu1H6az_b3NkmRn3VV4idJbbaIFcYcVoPidI-v7641Xeik5Elberg_sfxgbH0zunkvD75ByJvZ_j75-kSiYFicTTVMhmUNv8LICstjdXYvuShhsGjqIGu-_74LZ9TyX8B7Wn6lai81mGmn1MuWV9tvuyB853xmzfb4yEy6ly3Qdrs2H8cVoQKszkcwAEJDT85Rd8EUN1-zMW1J12lPFxiImYMPxs8uaHaulTa2hzls8YsyDL6gXfttKCqEmpz9Hppk_hbb7h0cwKb8BUklVbQ
{
    "email": "javier@gmail.com",
    "password": "123456"
}

### 2. Iniciar sesión para conseguir el Token (POST)
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "email": "javier@gmail.com",
    "password": "123456"
}

### 3. Crear una tarea USANDO EL TOKEN (POST)
POST http://127.0.0.1:8000/api/tareas/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjM3MzAwNzY5YTA3ZTA1MTE2ZjdlNTEzOGZhOTA5MzY4NWVlYmMyNDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZWNvLXRlY2gtOWRmZWEiLCJhdWQiOiJlY28tdGVjaC05ZGZlYSIsImF1dGhfdGltZSI6MTc3NDQxMjAzMywidXNlcl9pZCI6IlI2OTd4MW81VzVPRFpqcFlhbkJSYkFEektndTEiLCJzdWIiOiJSNjk3eDFvNVc1T0RaanBZYW5CUmJBRHpLZ3UxIiwiaWF0IjoxNzc0NDEyMDMzLCJleHAiOjE3NzQ0MTU2MzMsImVtYWlsIjoiamF2aWVyQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqYXZpZXJAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.dAeCNVHhX5Ps3lBHjeblPX_cgZMugymOmZXt_JzEpOYQUoIjlrpnF5RYBmaIc-Dx0mu1H6az_b3NkmRn3VV4idJbbaIFcYcVoPidI-v7641Xeik5Elberg_sfxgbH0zunkvD75ByJvZ_j75-kSiYFicTTVMhmUNv8LICstjdXYvuShhsGjqIGu-_74LZ9TyX8B7Wn6lai81mGmn1MuWV9tvuyB853xmzfb4yEy6ly3Qdrs2H8cVoQKszkcwAEJDT85Rd8EUN1-zMW1J12lPFxiImYMPxs8uaHaulTa2hzls8YsyDL6gXfttKCqEmpz9Hppk_hbb7h0cwKb8BUklVbQ

{
    "titulo": "leelo porfa2",
    "descripcion": "ahora si deberia funcionar"
}

# ### 4. Eliminar una tarea (DELETE)
# POST http://127.0.0.1:8000/api/tareas/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZXZpZGVuY2lhMi1mZjNjOCIsImF1ZCI6ImV2aWRlbmNpYTItZmYzYzgiLCJhdXRoX3RpbWUiOjE3NzI1NzEyNjIsInVzZXJfaWQiOiJmMEI0U3NwZHRFT1NCY0RCRHJwSWpwT29OUEUzIiwic3ViIjoiZjBCNFNzcGR0RU9TQmNEQkRycElqcE9vTlBFMyIsImlhdCI6MTc3MjU3MTI2MiwiZXhwIjoxNzcyNTc0ODYyLCJlbWFpbCI6InpldGEyQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ6ZXRhMkBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.rH3sGJ4r264_LhHOm4BWEtCnNjbKIONZe7IzOuRPVLuz6yOc5GmIwxCwL3OkNWy7-UU72sonCXgnzTdetdRf0tRglZCJ5Eje2sRBQp0PPpy8AQu_0rV66SMcD4pogZRuIZCEbrARE3BkRhxFjr9RjRArxzt9YR6YGECWIfzBQfLf6_iyXmL5ZTKS5EvlK1p0lmGEz3ff_emX5hiKNQOF0bUYd_G7NjX_PP53FrB8FdyYy-jB6GEB82jkV0t5Wrxchc9puQni5Hz4nd0NOIKRv5IdKSI4tq8rtO0gI_a8emIEathA-YL_mDP973_Rbq148d340dJpLIzV_IlMw2sPWg

# {
#     "titulo": "leelo porfa2",
# }

### Eliminar una tarea


DELETE http://127.0.0.1:8000/api/tareas/UoKjQJFQ2zaZCn2WzDGU/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjM3MzAwNzY5YTA3ZTA1MTE2ZjdlNTEzOGZhOTA5MzY4NWVlYmMyNDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZWNvLXRlY2gtOWRmZWEiLCJhdWQiOiJlY28tdGVjaC05ZGZlYSIsImF1dGhfdGltZSI6MTc3NDQxMjAzMywidXNlcl9pZCI6IlI2OTd4MW81VzVPRFpqcFlhbkJSYkFEektndTEiLCJzdWIiOiJSNjk3eDFvNVc1T0RaanBZYW5CUmJBRHpLZ3UxIiwiaWF0IjoxNzc0NDEyMDMzLCJleHAiOjE3NzQ0MTU2MzMsImVtYWlsIjoiamF2aWVyQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqYXZpZXJAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.dAeCNVHhX5Ps3lBHjeblPX_cgZMugymOmZXt_JzEpOYQUoIjlrpnF5RYBmaIc-Dx0mu1H6az_b3NkmRn3VV4idJbbaIFcYcVoPidI-v7641Xeik5Elberg_sfxgbH0zunkvD75ByJvZ_j75-kSiYFicTTVMhmUNv8LICstjdXYvuShhsGjqIGu-_74LZ9TyX8B7Wn6lai81mGmn1MuWV9tvuyB853xmzfb4yEy6ly3Qdrs2H8cVoQKszkcwAEJDT85Rd8EUN1-zMW1J12lPFxiImYMPxs8uaHaulTa2hzls8YsyDL6gXfttKCqEmpz9Hppk_hbb7h0cwKb8BUklVbQ


###subir imagen de perfil al usuario

POST http://127.0.0.1:8000/api/perfil/foto/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjM3MzAwNzY5YTA3ZTA1MTE2ZjdlNTEzOGZhOTA5MzY4NWVlYmMyNDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZWNvLXRlY2gtOWRmZWEiLCJhdWQiOiJlY28tdGVjaC05ZGZlYSIsImF1dGhfdGltZSI6MTc3NDQxMjAzMywidXNlcl9pZCI6IlI2OTd4MW81VzVPRFpqcFlhbkJSYkFEektndTEiLCJzdWIiOiJSNjk3eDFvNVc1T0RaanBZYW5CUmJBRHpLZ3UxIiwiaWF0IjoxNzc0NDEyMDMzLCJleHAiOjE3NzQ0MTU2MzMsImVtYWlsIjoiamF2aWVyQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJqYXZpZXJAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.dAeCNVHhX5Ps3lBHjeblPX_cgZMugymOmZXt_JzEpOYQUoIjlrpnF5RYBmaIc-Dx0mu1H6az_b3NkmRn3VV4idJbbaIFcYcVoPidI-v7641Xeik5Elberg_sfxgbH0zunkvD75ByJvZ_j75-kSiYFicTTVMhmUNv8LICstjdXYvuShhsGjqIGu-_74LZ9TyX8B7Wn6lai81mGmn1MuWV9tvuyB853xmzfb4yEy6ly3Qdrs2H8cVoQKszkcwAEJDT85Rd8EUN1-zMW1J12lPFxiImYMPxs8uaHaulTa2hzls8YsyDL6gXfttKCqEmpz9Hppk_hbb7h0cwKb8BUklVbQ
Content-Type: multipart/form-data; boundary=MiBoundary

--MiBoundary
Content-Disposition: form-data; name="imagen"; filename="avatar.jpg"
Content-Type: image/jpeg

C:\Users\DAYANA CASTAÑEDA\Downloads/avatar.jpg
--MiBoundary--  